version: "3"
services: 
    app:
        container_name: fronted_api_final_exam
        build: 
            dockerfile: Dockerfile
            context: .
        volumes: 
            - /app/node_modules
            - .:/app
            - ./src:/app/src
        ports: 
            - "3000:3000"
        links: 
            - mongo
    mongo:
        image: mongo:4.4.4
        volumes: 
            - ./data/db:/data/db
        ports: 
            - "27017:27017"